name: best
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_speed_dial: 6.0.0
  fluttertoast: 8.0.9
  fancy_bottom_navigation: 0.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
